#rvm: 
#  - 1.8.7
#  - 1.9.3
branches:
  only:
    - master
notifications:
  email: false
#env:
#  - PUPPET_VERSION=2.6.17
#  - PUPPET_VERSION=2.7.20
#  - PUPPET_VERSION=3.1.0
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_VERSION=2.7.20
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.20
    - rvm: 1.8.7
      env: PUPPET_VERSION=3.1.0
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.1.0
#  exclude:
#    - rvm: 1.8.7
#      env: PUPPET_VERSION=3.1.0
#    - rvm: 1.9.3
#      env: PUPPET_VERSION=2.6.17
#
